import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const arigato = localFont({
  src: "./fonts/arigato.ttf",
  variable: "--font-arigato",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Sheikh Jamir Alam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${arigato.variable} antialiased`}>{children}</body>
    </html>
  );
}
